tokens:
  - name: bridge-token-0
    secret: zTXL+SyC...
  - name: bridge-token-1
    secret: vbTlSX3W...
bridge:
  pool_name: pool1
  pool_id: d0729483-689f-400c-9925-e8a0f11424b1
  user_email: user@company.com
  pod_url: prod-useast-a.online.tableau.com
  site_name: tableausitename
  db_drivers:
    - amazon_athena
    - amazon_emr_hadoop_hive
    - amazon_redshift
    - cloudera_hive
